image: fedora/32
packages:
  - python
  - python-pip
sources:
  - https://git.sr.ht/~ruivieira/python-experiments
tasks:
  - setup: |
      cd python-experiments
      pip install --user poetry --progress-bar off
      poetry install
  - lint: |
      cd python-experiments
      pylint $(git ls-files '*.py')
  - typing: |
      cd python-experiments
      mypy $(git ls-files '*.py')
