image: fedora/32
packages:
  - python
  - python-pip
sources:
  - https://git.sr.ht/~ruivieira/python-experiments
tasks:
  - setup: |
      cd python-experiments
      pip install -r requirements.txt
      pip install -r requirements-test.txt
  - lint: |
      cd python-experiments
      pylint $(git ls-files '*.py')
  - typing: |
      cd python-experiments
      mypy $(git ls-files '*.py')
  - formatting: |
      cd python-experiments
      black --check $(git ls-files '*.py')
