image: fedora/32
packages:
  - python
  - python-pip
sources:
  - https://git.sr.ht/~ruivieira/python-experiments
tasks:
  - setup: |
      cd python-experiments
      pip install --user poetry --progress-bar off
      poetry install --no-root
  - lint: |
      cd python-experiments
      poetry run pylint $(git ls-files '*.py')
  - typing: |
      cd python-experiments
      poetry run mypy $(git ls-files '*.py')
  - formatting: |
      cd python-experiments
      poetry run black --check $(git ls-files '*.py')
