image: fedora/32
packages:
  - python
  - python-pip
sources:
  - https://git.sr.ht/~ruivieira/python-experiments
tasks:
  - setup: |
      cd python-experiments
      pip install -r requirements.txt --user
      pip install -r requirements-test.txt --user
  - lint: |
      cd python-experiments
      pylint $(git ls-files '*.py')