name: Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture: x64

      - name: Install Dependencies
        run: |
          pip install - r requirements.txt
          pip install - r requirements-test.txt

      - name: Lint
        run: pylint $(find . -type f -name "*.py")

      - name: Typings
        run: mypy $(find . -type f -name "*.py")

      - name: Formatting
        run: black --check $(find . -type f -name "*.py")